AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - '.idea/**/*'
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 100

Style/RedundantReturn:
  # When `true` allows code like `return x, y`.
  AllowMultipleReturnValues: false
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: braces
