sudo: required

env:
  # You may want to update this to whatever the latest version is, or keep it
  # the same as your local machines. However, I have only tested it with 1.8.0+.
  # There should be a time in the future when this is not necessary - it is
  # explained in more detail below.
  DOCKER_COMPOSE_VERSION: 1.8.0

services:
  - docker

before_install:
  # By default Travis CI has Postgres running, stop the service.
  - sudo service postgresql stop

  - docker-compose --version
  - docker-compose pull
  - docker-compose build
  - docker ps

  # Initialize the database.
  - docker-compose run web rake db:create

script:
  # Runs the lint check for the code
  - docker-compose run web rubocop
  # Runs all tests
  - docker-compose run web rails test
